before_script:
  - "apt-get update; apt-get install -y build-essential git libnuma-dev"

stages:
  - build
  - test

compile:
  image: ubuntu:xenial
  stage: build
  artifacts:
    - test/*-test
    - lib*.so
    expire_in: 1 week
  script:
    - make

basetest:
  image: ubuntu:xenial
  stage: test
  dependencies:
    - compile
  script:
    - test/context-test
    - test/channel-test

shmtest:
  image: ubuntu:xenial
  stage: test
  dependencies:
    - compile
  script:
    - "test/queuepair-test shm"
    - test/shm-queue-test

fftest:
  image: ubuntu:xenial
  stage: test
  dependencies:
    - compile
  script:
    - "test/queuepair-test ffq"
