image: stefankaestle/gcc

before_script:
  - "apt-get update; apt-get install -y git libnuma-dev build-essential"

# BUILD
# --------------------------------------------------

stages:
  - build
  - test

compile:
  stage: build
  artifacts:
    paths:
      - test/*-test
      - lib*.so
    expire_in: 1 week
  script:
    - make

debug-compile:
  stage: build
  script:
    - "BUILDTYPE=debug make"

# EXECUTE
# --------------------------------------------------

basetest:
  stage: test
  dependencies:
    - compile
  script:
    - "export LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH"
    - "test/queuepair-test ump"
    - test/context-test
    - test/channel-test

shmtest:
  stage: test
  dependencies:
    - compile
  script:
    - "export LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH"
    - "test/queuepair-test shm"
    - test/shm-queue-test

fftest:
  stage: test
  dependencies:
    - compile
  script:
    - "export LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH"
    - "test/queuepair-test ffq"
