stages:
  - build
  - test

compile:
  image: stefankaestle/gcc
  stage: build
  artifacts:
    paths:
      - test/*-test
      - lib*.so
    expire_in: 1 week
  script:
    - make

basetest:
  image: stefankaestle/gcc
  stage: test
  dependencies:
    - compile
  script:
    - "export LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH"
    - "test/queuepair-test ump"
    - test/context-test
    - test/channel-test

shmtest:
  image: stefankaestle/gcc
  stage: test
  dependencies:
    - compile
  script:
    - "export LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH"
    - "test/queuepair-test shm"
    - test/shm-queue-test

fftest:
  image: stefankaestle/gcc
  stage: test
  dependencies:
    - compile
  script:
    - "export LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH"
    - "test/queuepair-test ffq"
