before_script:
  - "apt-get update; apt-get install -y build-essential git libnuma-dev"

stages:
  - build
  - test

compile:
  image: ubuntu:xenial
  stage: build
  script:
    - make

basetest:
  image: ubuntu:xenial
  stage: test
  script:
    - test/context-test
    - test/channel-test

shmtest:
  image: ubuntu:xenial
  stage: test
  script:
    - test/shm-queue-test
