/*
 * Copyright (c) 2016 ETH Zurich.
 * All rights reserved.
 *
 * This file is distributed under the terms in the attached LICENSE file.
 * If you do not find this file, copies can be found by writing to:
 * ETH Zurich D-INFK, Universitaetstr. 6, CH-8092 Zurich. Attn: Systems Group.
 */
#include <smlt.h>
#include <smlt_generator.h>

/**
 * @brief generates a model using the simulator
 *
 * @param cores         an arry of cores that contains the
 *                      cores of the model
 * @param len           length of the cores array
 * @param name          name of the tree topology generated by the
 *                      simulator
 * @param mode          pointer to the model encoded as an uint16_t array
 * @param leafs         pointer to the leaf nodes array
 * @param last_node     pointer to the value of the last node
 *
 */
void smlt_generate_model(coreid_t* cores, uint32_t len,
                         const char* name, uint16_t** model,
                         uint32_t** leafs, uint32_t* last_node)
{

}
/**
 * @brief generates a model from a file storing a json string
 *
 * @param filepath      path to the file
 * @param mode          pointer to the model encoded as an uint16_t array
 * @param leafs         pointer to the leaf nodes array
 * @param last_node     pointer to the value of the last node
 *
 */
void smlt_generate_modal_from_file(char* filepath, uint16_t** model, 
                                   uint32_t** leafs, uint32_t* last_node)
{

}

